version: '3'

services:
    webserver_offlex_kolkmedia: &laravel-template
      image: webserver_offlex_kolkmedia:latest
      build:
        context: .
        dockerfile: ./Dockerfile
      container_name: webserver_offlex_kolkmedia
      expose:
        - 80
      volumes:
        - .:/var/www/html:delegated
        - ./offlex_base:/var/www/html/offlex_base
        - ./public_html:/var/www/html/public_html
      depends_on:
        - db_offlex_kolkmedia
      links:
        - db_offlex_kolkmedia
      environment:
        - DB_PORT=33061
        - DB_HOST=db_offlex_kolkmedia
        - VIRTUAL_HOST=kolkmedia.offlex
        - VIRTUAL_PORT=80

    db_offlex_kolkmedia:
      container_name: db_offlex_kolkmedia
      build:
        context: .
        dockerfile: ./database/Dockerfile
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=offlex
        - MYSQL_ROOT_HOST=%
      volumes:
        - ./database/mysql_db:/var/lib/mysql
        - ./docker/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      expose:
        - 3306
      ports:
        - 33061:3306    

networks:
  default:
    external:
      name: nginx-proxy        