version: '3'

services:
    webserver_offlex_besoof: &laravel-template
      image: webserver_offlex_besoof:latest
      container_name: webserver_offlex_besoof
      build:
        context: .
        dockerfile: ./Dockerfile
      expose:
        - 80
      volumes:
        - .:/var/www/html:delegated
        - ./offlex_base:/var/www/html/offlex_base
        - ./public_html:/var/www/html/public_html
      # depends_on:
      #   - db_offlex_besoof
      # links:
      #   - db_offlex_besoof
      environment:
        - DB_PORT=33061
        - DB_HOST=db_offlex_besoof
        - VIRTUAL_HOST=besoof.offlex
        - VIRTUAL_PORT=80
      restart: unless-stopped  

    # db_offlex_besoof:
    #   container_name: db_offlex_besoof
    #   build:
    #     context: .
    #     dockerfile: ./database/Dockerfile
    #   environment:
    #     - MYSQL_ROOT_PASSWORD=root
    #     - MYSQL_DATABASE=offlex
    #     - MYSQL_ROOT_HOST=%
    #   volumes:
    #     - ./database/mysql_db:/var/lib/mysql
    #     - ./docker/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    #   expose:
    #     - 3306
    #   ports:
    #     - 33061:3306
    #   restart: unless-stopped  

networks:
  default:
    external: true
    name: nginx-proxy